---
title: "Control de calidad de datos de temperatura máxima para clustering de estaciones meteorológicas"
subtitle: "Series Temporales - Trabajo práctico final"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: styles.css
---


```{r global, include=FALSE}
require(gstat)
require(raster)
require(rgdal)
require(anomalize)
require(automap)
require(Cairo)
require(dplyr)
require(factoextra)
require(ggdendro)
require(ggplotify)
require(highcharter)
require(httr)
require(jsonlite)
require(leaflet)
require(leafem)
require(purrr)
require(sf)
require(stlplus)
require(stars)
require(tidyr)
require(TSclust)
require(zoo)

# Carga de shape de Argentina
argentina  <- base::readRDS("data/gadm36_ARG_0_sf.rds")

### Carga de datos para imputacion
load("data/SeriesInterpoladas.RData")
estaciones.estudio <- estaciones.estudio %>%
  dplyr::arrange(nombre)

### Datos para clustering
sample.datos <- series.interpoladas %>% 
  dplyr::inner_join(dplyr::select(estaciones.estudio, omm_id, nombre), by = c("omm_id")) %>%
  dplyr::mutate(id = paste(omm_id, nombre)) %>%
  dplyr::select(id, fecha, valor) %>% 
  tidyr::pivot_wider(names_from = "id", values_from = "valor") %>% 
  zoo::read.zoo(index.column = "fecha") %>% 
  zoo::na.locf() %>% 
  zoo::na.locf(fromLast= TRUE) %>% 
  zoo::na.trim(is.na= "any", sides= "left")
ds.matrix <- sample.datos %>%
  as.ts() %>%
  TSclust::diss("CORT")
clustering <- stats::hclust(d = ds.matrix, method = "ward.D2")  
colores <- c(
  '#299696',
  '#e11584',
  '#23a02c',
  '#9de043',
  '#e31a1c', #5
  '#fdbf6f',
  '#ef7f00',
  '#0f3923',
  '#1f78b4',
  '#6a3d9a', # 10
  '#fec5e5',
  "#7f7f7f",
  '#b15928',
  "#541e1b",
  "#fa8072"  #15
)
```

Detección de anomalías
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

Seleccione la estación para realizar la detección de _anomalías_ en la serie temporal de temperatura máxima.

```{r}
opcionesEstacionesAnomalias        <- dplyr::pull(estaciones.estudio, omm_id)
names(opcionesEstacionesAnomalias) <- dplyr::pull(estaciones.estudio, nombre)
shiny::selectInput(inputId = "estacionAnomaliasId",
                   label = shiny::div(icon("globe", lib = "glyphicon"), span(style = "padding-left: 5px;", "Estación")), 
                   choices = opcionesEstacionesAnomalias)
```

Indique el nivel de significancia para el test E-S-D que detectará las potenciales anomalías.

```{r}
shiny::sliderInput(inputId = "nivelSignificancia",
                   label = shiny::div(icon("scale", lib = "glyphicon"), span(style = "padding-left: 5px;", "Nivel de significancia")), 
                   min = 0.01, max = 0.1, step = 0.01, value = 0.05)
```

Column
-----------------------------------------------------------------------

### Detección de anomalías en serie temporal de temperatura máxima

```{r}
highcharter::renderHighchart({
  # Filtras datos de estación
  serie.estacion <- series.interpoladas %>%
    dplyr::filter(omm_id == as.integer(input$estacionAnomaliasId)) %>%
    dplyr::select(fecha, valor) %>%
    zoo::read.zoo(index.column = "fecha") %>%
    zoo::na.approx()
  estacion <- estaciones.estudio %>%
    dplyr::filter(omm_id == as.integer(input$estacionAnomaliasId))
  
  # Detección de anomalías
  serie.deteccion <- data.frame(fecha = zoo::index(serie.estacion),
                                valor = zoo::coredata(serie.estacion)) %>%
    tibble::as_tibble()
  deteccion <- serie.deteccion %>%
    anomalize::time_decompose(valor, method = "stl", frequency = 365) %>%
    anomalize::anomalize(remainder, method = "gesd", alpha = input$nivelSignificancia) %>%
    dplyr::filter(anomaly == "Yes") %>%
    dplyr::mutate(title = paste0("!! ", observed, " ºC"), text = "Posible anomalía")
  
  # Grafico
  shiny::withProgress({
    highcharter::highchart(type = "stock") %>% 
      highcharter::hc_add_series(data = xts::as.xts(serie.estacion), id = "tmax", name = "Temperatura máxima") %>%
      highcharter::hc_add_series(data = deteccion, mapping = highcharter::hcaes(x = fecha), 
                                 name = "Anomalías", type = "flags", onSeries = "tmax") %>%
      highcharter::hc_xAxis(title = list(text = "Fecha")) %>%
      highcharter::hc_yAxis(title = list(text = "Temperatura máxima (ºC)")) %>%
      highcharter::hc_chart(type = 'line', zoomType = 'x', panning = TRUE, panKey = 'shift') %>%
      highcharter::hc_legend(enabled = TRUE, layout = "horizontal") %>%
      highcharter::hc_tooltip(shared = TRUE, valueDecimals = 2) %>%
      highcharter::hc_colors(c('#1b9e77','#e41a1c')) %>%
      highcharter::hc_title(text = "Detección de anomalías de temperatura máxima") %>%
      highcharter::hc_subtitle(text = paste0("Estación ", estacion$nombre, " (", estacion$omm_id, ")")) %>%
      highcharter::hc_exporting(enabled = TRUE) %>%
      highcharter::hc_add_theme(highcharter::hc_theme_flat())
  }, value = NULL, message = "Realizando detección de anomalías...")
})
```


Imputación de faltantes
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

Seleccione la estación para realizar la descomposición STL aditiva de su serie temporal de temperatura máxima.

```{r}
opcionesEstacionesImputacion        <- dplyr::pull(estaciones.estudio, omm_id)
names(opcionesEstacionesImputacion) <- dplyr::pull(estaciones.estudio, nombre)
shiny::selectInput(inputId = "estacionImputacionId",
                   label = shiny::div(icon("globe", lib = "glyphicon"), span(style = "padding-left: 5px;", "Estación")), 
                   choices = opcionesEstacionesImputacion)
```

Indique una fecha para la cual desee realizar la interpolación espacial del residuo de temperatura máxima.

```{r}
shiny::dateInput(inputId = "fechaInterpolacion",
                 label = shiny::div(icon("calendar", lib = "glyphicon"), span(style = "padding-left: 5px;", "Fecha para interpolación")), 
                 min = min(series.interpoladas$fecha), max = max(series.interpoladas$fecha), 
                 value = as.Date("2006-06-15"), language = "es")

interpolar <- shiny::reactive({
  if (! is.null(input$fechaInterpolacion)) {
    residuos <- estaciones.estudio %>%
    dplyr::inner_join(
      dplyr::filter(series.interpoladas, fecha == input$fechaInterpolacion),
      by = c("omm_id")
    )
    
    locations  <- dplyr::filter(residuos, ! is.na(remainder))
    variograma <- gstat::variogram(remainder ~ 1, data = locations)
    modelo     <- automap::autofitVariogram(formula = remainder ~ 1, input_data = sf::as_Spatial(locations))
    kriging    <- gstat::krige(remainder ~ 1, locations = locations, newdata = residuos, model = modelo$var_model) %>%
      dplyr::rename(residuo_prediccion = var1.pred, varianza = var1.var) %>%
      dplyr::mutate(omm_id = dplyr::pull(residuos, omm_id), residuo_original = dplyr::pull(residuos, remainder), 
                    error = residuo_prediccion - residuo_original)
  
    # Se genera el raster interpolado
    grilla.regular <- sf::st_make_grid(x = argentina, what = "centers", cellsize = c(0.1, 0.1))
    kriging.grilla <- gstat::krige(remainder ~ 1, locations = locations, newdata = grilla.regular, model = modelo$var_model)
    kriging.arg    <- as(stars::st_rasterize(sf = kriging.grilla), "Raster") %>%
      raster::mask(x = ., mask = argentina)
    
    return (list(locations = locations, modelo = modelo, kriging = kriging.arg))
  }
  return (NULL)
})
```

Column
-----------------------------------------------------------------------

### Descomposición STL aditiva de serie temporal de temperatura máxima

```{r}
highcharter::renderHighchart({
  estacion <- estaciones.estudio %>%
    dplyr::filter(omm_id == as.integer(input$estacionAnomaliasId))
  serie.estacion <- series.interpoladas %>%
    dplyr::filter(omm_id == as.integer(input$estacionImputacionId)) %>%
    dplyr::select(fecha, valor, seasonal, trend, remainder, valor_interpolado)
    
  shiny::withProgress({
    highcharter::highchart(type = "stock") %>% 
      highcharter::hc_add_series(data = xts::xts(serie.estacion$trend, order.by = serie.estacion$fecha), 
                                 id = "trend", name = "Tendencia") %>%
      highcharter::hc_add_series(data = xts::xts(serie.estacion$seasonal, order.by = serie.estacion$fecha), 
                                 id = "seasonal", name = "Estacionalidad") %>%
      highcharter::hc_add_series(data = xts::xts(serie.estacion$remainder, order.by = serie.estacion$fecha), 
                                 id = "remainder", name = "Residuo") %>%
      highcharter::hc_add_series(data = xts::xts(serie.estacion$valor_interpolado, order.by = serie.estacion$fecha), 
                                 id = "complete", name = "Serie completa") %>%
      highcharter::hc_xAxis(title = list(text = "Fecha")) %>%
      highcharter::hc_yAxis(title = list(text = "Valor (ºC)")) %>%
      highcharter::hc_chart(type = 'line', zoomType = 'x', panning = TRUE, panKey = 'shift') %>%
      highcharter::hc_legend(enabled = TRUE, layout = "horizontal") %>%
      highcharter::hc_tooltip(shared = TRUE, valueDecimals = 2) %>%
      highcharter::hc_colors(c('#e6ab02','#1b9e77','#377eb8','#e41a1c')) %>%
      highcharter::hc_title(text = "Descomposición STL aditiva de temperatura máxima") %>%
      highcharter::hc_subtitle(text = paste0("Estación ", estacion$nombre, " (", estacion$omm_id, ")")) %>%
      highcharter::hc_exporting(enabled = TRUE) %>%
      highcharter::hc_add_theme(highcharter::hc_theme_flat())
  }, value = NULL, message = "Realizando descomposición STL...")
})
```

Column
-----------------------------------------------------------------------

### Interpolación espacial de residuos de temperatura máxima {data-height=650}
 
```{r}
leaflet::renderLeaflet({
  # Obtener residuos para fecha seleccionada
  shiny::withProgress({
    resultado <- interpolar()
    if (! is.null(resultado)) {
      locations   <- resultado$locations
      kriging.arg <- resultado$kriging
      
      # Dibujar mapa
      valores.interpolados <- raster::values(kriging.arg)
      paleta.kriging       <- leaflet::colorBin(palette = "RdYlBu", domain = valores.interpolados, bins = 8,
                                                na.color = "transparent", reverse = TRUE)
      
      leaflet::leaflet(data = locations) %>%
        leafem::addMouseCoordinates() %>%
        leaflet::addTiles(map = ., urlTemplate = "//server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}") %>%
        leaflet::addRasterImage(x = kriging.arg, colors = paleta.kriging, group = "Kriging", layerId = "Kriging") %>%
        leaflet::addCircleMarkers(map = ., label = ~sprintf("%s", nombre), radius = 5, color = "black", fillColor = "black",
                                  weight = 1, labelOptions = leaflet::labelOptions(noHide = F, textOnly = TRUE, style = list(
            "color" = "red",
            "font-weight" = "bold",
            "box-shadow" = "3px 3px rgba(0,0,0,0.25)",
            "font-size" = "12px",
            "border-color" = "rgba(0,0,0,0.5)"
          )
        )) %>%
        leafem::addImageQuery(map = ., x = kriging.arg, type = "mousemove", digits = 2, prefix = "Residuo",
                          group = "Kriging", layerId = "Kriging") %>%
        leaflet::addLegend(position = "bottomright", pal = paleta.kriging, values = valores.interpolados,
                       title = "Residuos (ºC)", opacity = 1)
    }
  }, value = NULL, message = "Realizando kriging...")
})
```

### Variograma ajustado {data-height=350}

```{r}
renderPlot({
  # Variograma
  resultado <- interpolar()
  if (! is.null(resultado)) {
    grafico.variograma      <- plot(resultado$modelo, col = "tomato", plotit = FALSE)
    grafico.variograma$main <- ""
    grafico.variograma$xlab <- "Distancia (km)"
    grafico.variograma$ylab <- "Semivarianza"
    grafico.variograma      <- ggplotify::as.ggplot(grafico.variograma)  
    return (grafico.variograma)
  }
})
```

Clustering
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

Indique la cantidad de _grupos_ para realizar el clustering.

```{r}
shiny::sliderInput(inputId = "cantidadClusters",
                   label = shiny::div(icon("scale", lib = "glyphicon"), span(style = "padding-left: 5px;", "Cantidad de grupos")), 
                   min = 3, max = 15, step = 1, value = 3)
```

Column
-----------------------------------------------------------------------

### Distribución espacial de clusters

```{r}
leaflet::renderLeaflet({
  shiny::withProgress({
    # Generacion de datos para mapa
    grupos    <- stats::cutree(tree = clustering, k = input$cantidadClusters)
    groups_df <- data.frame(id = names(grupos), cluster = as.factor(grupos), row.names = NULL)
    locations <- estaciones.estudio %>%
      dplyr::mutate(id = paste(omm_id, nombre), latitud = sf::st_coordinates(.)[, 2],
                    longitud = sf::st_coordinates(.)[, 1]) %>%
      sf::st_set_geometry(NULL) %>%
      dplyr::inner_join(groups_df, by = c("id"))
    
    # Mapa
    leaflet::leaflet(data = locations) %>%
      leaflet::addTiles(map = ., urlTemplate = "//server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}") %>%
      leaflet::addCircleMarkers(lat = ~ latitud, lng = ~ longitud, radius = 7, fillColor = ~colores[cluster],
                                stroke = TRUE, weight = 1, fillOpacity = 0.8, opacity = 1, color = ~colores[cluster],
                                popup = ~sprintf("<b>%s (%d)</b><br>Lat.: %.3f<br>Lon.: %.3f<br>Elev: %.0f m <br>Cluster: %.i", 
                                                 nombre, omm_id, latitud, longitud, elevacion, cluster))
  }, value = NULL, message = "Realizando clustering...")
})
```

Column
-----------------------------------------------------------------------

### Dendrograma

```{r}
shiny::renderPlot({
  factoextra::fviz_dend(clustering, k = input$cantidadClusters, rect = TRUE,
                        show_labels = FALSE, cex = 0.3,  horiz = FALSE, labels_track_height = 1) +
    ggplot2::scale_y_log10() +
    ggplot2::labs(x = "Estaciones", y = "Distancia (escala logarítmica)", title = "Dendrograma para estaciones meteorológicas",
                  subtitle = "Agrupación según series temporales de temperatura máxima 2001-2010") +
    ggplot2::theme_bw() +
    ggplot2::theme(
      text = ggplot2::element_text(size = 10),
      plot.title = ggplot2::element_text(hjust = 0.5),
      plot.subtitle = ggplot2::element_text(hjust = 0.5)
    )
})
```

### Índice de Silhouette

```{r}
shiny::renderPlot({
  factoextra::fviz_nbclust(as_data_frame(t(sample.datos)), FUN = hcut, method = "silhouette",
                           diss = ds.matrix, k.max = 25, print.summary = FALSE, barcolor='#000000',
                           verbose = FALSE) +
  ggplot2::labs(title = "Número óptimo de clusters", subtitle = "Evaluación mediante índice de Silhouette", 
                x = "Número de clusters", y = "Índice de Silhouette promedio") +
  ggplot2::geom_vline(xintercept = input$cantidadClusters, linetype = 2, 
                      size = 0.5, col = 'darkgreen') +
  ggplot2::theme_bw() +
  ggplot2::theme(
    text = ggplot2::element_text(size = 10),
    plot.title = ggplot2::element_text(hjust = 0.5),
    plot.subtitle = ggplot2::element_text(hjust = 0.5)
  )
})
```