---
date: "`r format(Sys.Date(), '%d de %B de %Y')`"
output: pdf_document
title: 'Visualización de la información: Trabajo Práctico nº 1'
subtitle: Superficie afectada por incendios forestales entre 2011 y 2016
author: 
  - Santiago Rovere (srovere@gmail.com), Facultad de Ciencias Exactas y Narutales (UBA)
lang: es
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE, results=FALSE }
# Borrar variables del ambiente
rm(list = objects())

# Carga de paquetes necesarios para hacer los gráficos
require(Cairo)
require(ggrepel)
require(sf)
require(tidyverse)

# Uso de Cairo para renderizar los gráficos
options(bitmapType = "cairo")

# Cargar shapes de provincias y departamentos
provincias    <- base::readRDS("shapes/gadm36_ARG_1_sf.rds")
departamentos <- sf::st_read(dsn = "shapes", layer = "ign_departamento")

# Cargar conjunto de datos
datos <- readr::read_delim(file = "dataset_incendios.csv", delim = ";") %>%
  dplyr::mutate(IN1 = paste0(provincia_id, departamento_id)) %>%
  dplyr::select(`año_inicial`, `año_final`, IN1, provincia, sup_afectada) %>%
  dplyr::rename(ano_inicio = `año_inicial`, ano_fin = `año_final`) %>%
  dplyr::filter(! is.na(sup_afectada))

# Definir categoria y color a cada dato de superficie afectada
intervalos <- c(-Inf, quantile(datos$sup_afectada, probs = seq(0.2, 0.8, 0.2)), Inf)
colores    <- c('#ffffb2','#fecc5c','#fd8d3c','#f03b20','#bd0026')
etiquetas  <- purrr::map(
    .x = seq(from = 1, to = length(intervalos) - 1, by = 1),
    .f = function(pos) {
      desde <- intervalos[pos]
      hasta <- intervalos[pos+1]
      if (is.infinite(desde)) {
        return (sprintf("Menos de %.2f Has", hasta))
      } else if (is.infinite(hasta)) {
        return (sprintf("Más de %.2f Has", desde))
      } else {
        return (sprintf("De %.2f a %.2f Has", desde, hasta))
      }
    }
  ) %>% unlist()

# Geolocalizar conjunto de datos y asignar categoria y color segun superficie afectada
datos.geolocalizados <- departamentos %>%
  dplyr::inner_join(datos, by = c("IN1")) %>%
  dplyr::select(IN1, provincia, sup_afectada) %>%
  dplyr::mutate(categoria = cut(x = sup_afectada, breaks = intervalos, labels = etiquetas))

# Generar resumen por provincia
resumen <- sf::st_set_geometry(datos.geolocalizados, NULL) %>%
  dplyr::group_by(provincia) %>%
  dplyr::summarise(area_afectada = sum(sup_afectada)) %>%
  dplyr::mutate(total = sum(area_afectada), porcentaje = 100*area_afectada/total) %>%
  dplyr::arrange(dplyr::desc(porcentaje)) 
otras.provincias <- resumen %>%
  dplyr::filter(porcentaje < 1) %>%
  dplyr::summarise(provincia = "Otras", porcentaje = sum(porcentaje), area_afectada = sum(area_afectada))
resumen.truncado <- resumen %>%
  dplyr::filter(porcentaje >= 1) %>%
  dplyr::bind_rows(otras.provincias) %>%
  dplyr::mutate(provincia = factor(provincia, levels = rev(provincia)))

# Generar serie temporal
serie.temporal <- dplyr::bind_rows(
  dplyr::distinct(datos, ano_inicio, IN1, sup_afectada) %>%
    dplyr::rename(ano = ano_inicio),
  dplyr::distinct(dplyr::filter(datos, ano_fin > ano_inicio), ano_fin, IN1, sup_afectada) %>%
    dplyr::rename(ano = ano_fin)
) %>% dplyr::group_by(ano) %>%
  dplyr::summarise(area_afectada = sum(sup_afectada))
```

```{r, echo=FALSE, warnings=FALSE, message=FALSE, fig.width=10, fig.height=10 }
# Generar inset 1 indicando evolucion temporal de areas incendiadas
inset1 <- ggplot2::ggplot(data = serie.temporal) +
  ggplot2::geom_area(mapping = ggplot2::aes(x = ano, y = area_afectada),
                     color = "red", fill = alpha("orange", 0.3), alpha = 0.7) +
  ggrepel::geom_label_repel(mapping = ggplot2::aes(x = ano, y = area_afectada, 
                                                   label = sprintf("%.0f Has", area_afectada)),
                            nudge_x = 0, nudge_y = 10, size = 3, segment.size = 0) +
  ggplot2::labs(x = "", y = "Superficie afectada (Has)", title = "Evolución temporal de área afectada") +
  ggplot2::theme_light() + 
  ggplot2::theme(
    plot.title = ggplot2::element_text(hjust = 0.5, size = 12)
  ) 
inset.tibble.1 <- tibble::tibble(x = 0.98, y = 0.90, plot = list(inset1))

# Generar inset 2 indicando porcentaje de area que le corresponde a cada provincia y la superficie total
inset2 <- ggplot2::ggplot(data = resumen.truncado) +
  ggplot2::geom_segment(mapping = ggplot2::aes(x = provincia, xend = provincia, y = 0, yend = porcentaje)) +
  ggplot2::geom_point(mapping = ggplot2::aes(x = provincia, y = porcentaje),
                      size = 3, color = "red", fill = alpha("orange", 0.3), alpha = 0.7, shape = 21, stroke = 2) +
  ggrepel::geom_label_repel(mapping = ggplot2::aes(x = provincia, y = porcentaje, 
                                                   label = sprintf("%.0f Has", area_afectada)),
                            nudge_x = 0, nudge_y = 10, size = 3, segment.alpha = 0) +
  ggplot2::labs(x = "", y = "Porcentaje", title = "Distribución provincial de área afectada",
                subtitle = "Porcentaje de área respecto del total afectado") +
  ggplot2::scale_y_continuous(limits = c(0, 50)) +
  ggplot2::theme_light() + 
  ggplot2::theme(
    plot.title = ggplot2::element_text(hjust = 0.5, size = 12),
    plot.subtitle = ggplot2::element_text(hjust = 0.5, size = 10),
    legend.position = 'none'
  ) + ggplot2::coord_flip()

# Generar tibble con insets
inset.tibble <- tibble::tibble(
  x = c(0.98, 0.98), y = c(0.98, 0.07), 
  vp.width = c(0.4, 0.6), vp.height = c(0.45, 0.45),
  plot = list(inset1, inset2)
)

# Dibujar mapa
ggplot2::ggplot() +
  ggpmisc::geom_plot_npc(data = inset.tibble, 
                         mapping = ggplot2::aes(npcx = x, npcy = y, label = plot, vp.width = vp.width, vp.height = vp.height)) +
  ggplot2::geom_sf(data = provincias, colour = "black", fill = "#dbdbdb", size = 0.1) +
  ggplot2::geom_sf(data = datos.geolocalizados, colour = NA,
                   mapping = ggplot2::aes(fill = categoria)) +
  ggplot2::annotate(geom = "text", x = -65, y = -60, parse = TRUE,
                    label = "paste(bold(\"Fuente:\"), \" https://datos.gob.ar/dataset/ambiente-incendios-forestales\")") +
  ggplot2::coord_sf(xlim = c(-80, -25), ylim = c(-60, -20)) +
  ggplot2::labs(x = "", y = "") +
  ggplot2::scale_fill_manual(name = "Superficie afectada", values = colores, labels = etiquetas) +
  ggplot2::theme_bw() +
  ggplot2::theme(
    panel.grid.major = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_blank(),
    axis.ticks.x = ggplot2::element_blank(),
    axis.text.y = ggplot2::element_blank(),
    axis.ticks.y = ggplot2::element_blank(),
    strip.text.x = ggplot2::element_blank(),
    strip.background = ggplot2::element_rect(colour = "white", fill = "white"),
    legend.position = c(0.11, 0.88),
    legend.background = ggplot2::element_rect(fill = "grey90", size = 0.1, linetype = "solid", colour = "black")
  )
```

