# ------------------------------------------------------------------------------
# Variables a validar
# ------------------------------------------------------------------------------
variables : [ 'prcp', 'tmin', 'tmax' ] 
# ------------------------------------------------------------------------------
 
# ------------------------------------------------------------------------------
# Umbral de precipitación
# ------------------------------------------------------------------------------
umbral.precipitacion: 0.1 # Umbral de definición de día lluvioso
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Archivo donde se guarda el resporte
# ------------------------------------------------------------------------------
output.file : "ValidacionSeriesSinteticas.html" # Nombre del archivo de salida
# ------------------------------------------------------------------------------
