# ------------------------------------------------------------------------------
# Constantes a utilizar por pais
# ------------------------------------------------------------------------------
constantes:
  bristow.campbell:
    - { omm_id: [], A: 0.69, B: 0.02, C: 2.12 }
    - { omm_id: [], A: 0.714, B: 0.007, C: 2.26 }
    - { omm_id: [ 86430, 86490, 86560, 90000001, 90000002 ], A: 0.69, B: 0.02, C: 2.12 }
# ------------------------------------------------------------------------------