---
date: "`r format(Sys.Date(), '%d de %B de %Y')`"
output: pdf_document
title: 'Sistemas de información geográfica: Trabajo Práctico nº 1'
subtitle: 'Análisis del acceso a la educación primaria en la Ciudad de Buenos Aires'
author: 
  - Aprea, Mariano
  - Estrin, Hernán
  - Pecina, Lucas
  - Rovere, Santiago (srovere@gmail.com)
lang: es
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE, results=FALSE }
# Borrar variables del ambiente
rm(list = objects())

# Carga de paquetes necesarios para hacer los gráficos
require(Cairo)
require(sf)
require(tidyverse)

# Uso de Cairo para renderizar los gráficos
options(bitmapType = "cairo")

# Cargar datos de barrios
barrios <- sf::st_read(dsn = "data", layer = "barrios_badata") %>%
  dplyr::mutate(barrio_id = dplyr::row_number(), area = AREA/1000000) %>%
  dplyr::rename(comuna = COMUNA, nombre = BARRIO) %>%
  dplyr::select(barrio_id, comuna, nombre, area)

# Cargar contorno de CABA, obtener geometria
contorno <- geojsonsf::geojson_sf("data/contorno_caba.geojson") %>%
  sf::st_transform(crs = sf::st_crs(barrios)) %>%
  sf::st_geometry()

# Cargar datos de establecimientos y determinar a que barrio pertenece cada uno de ellos
# Me quedo con las escuelas estatales de nivel primario
establecimientos <- sf::st_read(dsn = "data", layer = "establecimientos-educativos") %>%
  dplyr::mutate(barrio_id = as.integer(unlist(sf::st_intersects(., barrios)))) %>%
  dplyr::filter(SECTOR == 1 & stringr::str_detect(string = NIVMOD, pattern = "PriCom")) %>%
  dplyr::rename(establecimiento_id = OBJECTID)

# Determinar poligonos de influencia para los establecimientos
influencia.establecimientos <- sf::st_intersection(sf::st_cast(sf::st_voronoi(sf::st_union(establecimientos), contorno)), contorno) %>%
  sf::st_as_sf() %>%
  dplyr::rename(geometry = x) %>%
  dplyr::mutate(poligono_influencia_id = dplyr::row_number())

# Determinar pertenencia de establecimientos a poligonos
establecimientos <- establecimientos %>%
  dplyr::mutate(poligono_influencia_id = as.integer(sf::st_intersects(establecimientos, influencia.establecimientos)))

# Aplicamos lo mismo para los privados por si son necesarios
# Les asociamos los poligonos de influencia de los establecimientos publicos
establecimientos.privados <- sf::st_read(dsn = "data", layer = "establecimientos-educativos") %>%
  dplyr::mutate(barrio_id = as.integer(unlist(sf::st_intersects(., barrios)))) %>%
  dplyr::filter(SECTOR == 2 & stringr::str_detect(string = NIVMOD, pattern = "PriCom")) %>%
  dplyr::rename(establecimiento_id = OBJECTID) %>%
  dplyr::mutate(poligono_influencia_id = as.integer(sf::st_intersects(., influencia.establecimientos)))

# Cargar datos censales, pasar a proyeccion planar y determinar a que barrio pertenece cada uno de ellos
# Dado que los radios censales estan incluidos dentro de un barrio, entonces para evitar problemas de proyeccion
# se determinarar el barrio en base a la ubicacion del centroide. Se utiliza st_nearest_feature porque para
# 4 casos en particular, el centroide cae fuera del poligono de barrios (por los "huecos" que tiene)
# Como el archivo de censos tiene mal 2 poligonos, los extraigo del geojson y luego hago join con los datos censales.
# Utilizando los centroides de los radios censales, determinar la pertenencia a los poligonos de influencia.
radios.censales <- geojsonsf::geojson_sf("data/caba_radios_censales.geojson") %>%
  sf::st_transform(crs = sf::st_crs(barrios)) %>%
  dplyr::select(-BARRIO)
datos.censales <- sf::st_read(dsn = "data", layer = "censo_2010_caba") %>%
  sf::st_transform(crs = sf::st_crs(barrios)) %>%
  dplyr::select(CO_FRAC_RA, T_VARON, T_MUJER, T_VIVIENDA, V_PARTICUL, V_COLECTIV) %>%
  dplyr::rename(RADIO_ID = CO_FRAC_RA) %>%
  sf::st_set_geometry(NULL)
censo <- dplyr::inner_join(radios.censales, datos.censales, by = c("RADIO_ID"))
centroides.radios.censales <- sf::st_centroid(censo) %>%
  dplyr::mutate(barrio_id = as.integer(sf::st_nearest_feature(., barrios)),
                poligono_influencia_id = as.integer(sf::st_intersects(., influencia.establecimientos))) %>%
  sf::st_set_geometry(NULL) %>%
  dplyr::select(RADIO_ID, barrio_id, poligono_influencia_id) %>%
  dplyr::filter(! is.na(barrio_id) & ! is.null(poligono_influencia_id))
censo <- censo %>%
  dplyr::inner_join(centroides.radios.censales, by = "RADIO_ID")

# Cargar paradas de transportes publicos
count.true <- function(...) {
  purrr::pmap(
    .l = list(...),
    .f = function(...) {
      p <- list(...)
      length(which(as.logical(p)))
    }
  ) %>% unlist()
}
paradas.transporte.publico <- sf::st_read(dsn = "data", layer = "public_transport_stops_caba") %>%
  dplyr::select(full_id, name, railway, public_tra, bus, railway, train, tram) %>%
  dplyr::mutate(is_bus = (bus == "yes"), is_railway = ! is.na(railway), is_train = (train == "yes"), is_tram = (tram == "yes"),
                type_count = count.true(is_bus, is_railway, is_train, is_tram),
                parada_id = dplyr::n()) %>%
  dplyr::filter(! (is.na(bus) & is.na(railway) & is.na(train) & is.na(tram))) %>%
  sf::st_transform(sf::st_crs(establecimientos))

# Buscar senderos escolares
senderos.escolares <- sf::st_read(dsn = "data", layer = "senderos-escolares") %>%
  dplyr::rename(longitud_total_km = Longitud) %>%
  sf::st_transform(sf::st_crs(barrios)) %>%
  sf::st_intersection(x = ., y = dplyr::select(barrios, barrio_id)) %>%
  dplyr::mutate(longitud = sf::st_length(geometry))

# Guardar datos para aplicacion Shiny y eliminar variables innecesarias
save(barrios, censo, contorno, establecimientos, establecimientos.privados, senderos.escolares,
     influencia.establecimientos, paradas.transporte.publico, file = "sdig-2020-tp1/Dataset.RData")
rm(radios.censales, datos.censales, centroides.radios.censales)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE, results=TRUE }
# Porcentaje de hogares NBI por barrio
escala.limites         <- c(-Inf, 1, 2, 5, 10, 15, 20, Inf)
escala.colores         <- c('#ffffb2','#fed976','#feb24c','#fd8d3c','#fc4e2a','#e31a1c','#b10026')
escala.etiquetas       <- c('Hasta 1%','De 1% a 2%','De 2% a 5%','De 5% a 10%', 'De 10% a 15%', 'De 15% a 20%', 'Más de 20%')
hogares.nbi.por.barrio <- censo %>%
  sf::st_set_geometry(NULL) %>%
  dplyr::group_by(barrio_id) %>%
  dplyr::summarise(hogares_nbi = sum(HOGARES_NBI), hogares = sum(HOGARES)) %>%
  dplyr::mutate(porcentaje = 100 * hogares_nbi / hogares,
                escala = cut(x = porcentaje, breaks = escala.limites))
hogares.nbi.por.barrio <- barrios %>%
  dplyr::inner_join(hogares.nbi.por.barrio, by = c("barrio_id"))

ggplot2::ggplot() +
  ggplot2::geom_sf(data = hogares.nbi.por.barrio, colour = "black",
                   mapping = ggplot2::aes(fill = escala)) +
  ggplot2::labs(x = "", y = "", title = "Porcentaje de hogares NBI por barrio",
                subtitle = "",
                fill = "Porcentaje") +
  ggplot2::scale_fill_manual(values = escala.colores, labels = escala.etiquetas) +
  ggplot2::theme_bw() +
  ggplot2::theme(
    plot.title = ggplot2::element_text(hjust = 0.5),
    plot.subtitle = ggplot2::element_text(hjust = 0.5),
    panel.grid.major = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_blank(),
    axis.ticks.x = ggplot2::element_blank(),
    axis.text.y = ggplot2::element_blank(),
    axis.ticks.y = ggplot2::element_blank(),
    strip.text.x = ggplot2::element_blank(),
    strip.background = ggplot2::element_rect(colour = "white", fill = "white"),
    legend.position = "right",
    legend.background = ggplot2::element_rect(fill = "grey90", size = 0.1, linetype = "solid", colour = "black")
  )
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE, results=TRUE }
# Mapas de establecimientos por km2 de cada barrio
establecimientos.por.barrio <- establecimientos %>%
  sf::st_set_geometry(NULL) %>%
  dplyr::group_by(barrio_id) %>%
  dplyr::summarise(cantidad = dplyr::n())
establecimientos.por.barrio <- barrios %>%
  dplyr::inner_join(establecimientos.por.barrio, by = c("barrio_id")) %>%
  dplyr::mutate(densidad = cantidad / area)

ggplot2::ggplot() +
  ggplot2::geom_sf(data = establecimientos.por.barrio, colour = "black",
                   mapping = ggplot2::aes(fill = densidad)) +
  ggplot2::labs(x = "", y = "", title = "Establecimientos educativos por barrio",
                subtitle = "Densidad por km²",
                fill = "Densidad") +
  ggplot2::scale_fill_distiller(type = "seq", palette = "YlOrRd", direction = 1) +
  ggplot2::theme_bw() +
  ggplot2::theme(
    plot.title = ggplot2::element_text(hjust = 0.5),
    plot.subtitle = ggplot2::element_text(hjust = 0.5),
    panel.grid.major = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_blank(),
    axis.ticks.x = ggplot2::element_blank(),
    axis.text.y = ggplot2::element_blank(),
    axis.ticks.y = ggplot2::element_blank(),
    strip.text.x = ggplot2::element_blank(),
    strip.background = ggplot2::element_rect(colour = "white", fill = "white"),
    legend.position = "right",
    legend.background = ggplot2::element_rect(fill = "grey90", size = 0.1, linetype = "solid", colour = "black")
  ) + ggplot2::guides(fill = ggplot2::guide_colourbar(barheight = 10))
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE, results=TRUE }
# Para cada poligono de influencia, calcular la cantidad de hogares NBI por establecimiento
escala.limites           <- c(-Inf, 50, 100, 250, 500, Inf)
escala.colores           <- c('#ffffb2','#fecc5c','#fd8d3c','#f03b20','#bd0026')
escala.etiquetas         <- c('Hasta 50','De 51 a 100','De 101 a 250','De 250 a 500', 'Más de 500')
hogares.nbi.por.poligono <- sf::st_set_geometry(censo, NULL) %>%
  dplyr::select(poligono_influencia_id, HOGARES, HOGARES_NBI) %>%
  dplyr::group_by(poligono_influencia_id) %>%
  dplyr::summarise(hogares = sum(HOGARES), hogares_nbi = sum(HOGARES_NBI))
establecimientos.por.poligono <- sf::st_set_geometry(establecimientos, NULL) %>%
  dplyr::group_by(poligono_influencia_id) %>%
  dplyr::summarise(establecimientos = dplyr::n())
hogares.establecimientos.poligonos <- influencia.establecimientos %>%
  dplyr::left_join(hogares.nbi.por.poligono, by = c("poligono_influencia_id")) %>%
  dplyr::left_join(establecimientos.por.poligono, by = c("poligono_influencia_id")) %>%
  dplyr::mutate(hogares_nbi_establecimiento = hogares_nbi / establecimientos,
                escala = cut(x = hogares_nbi_establecimiento, breaks = escala.limites))

ggplot2::ggplot() +
  ggplot2::geom_sf(data = hogares.establecimientos.poligonos, colour = "black",
                   mapping = ggplot2::aes(fill = escala)) +
  ggplot2::labs(x = "", y = "", title = "Hogares NBI por establecimientos educativos",
                subtitle = "",
                fill = "Hogares NBI") +
  ggplot2::scale_fill_manual(values = c(escala.colores, "#7f7f7f"), 
                             labels = c(escala.etiquetas, "Sin datos")) +
  ggplot2::theme_bw() +
  ggplot2::theme(
    plot.title = ggplot2::element_text(hjust = 0.5),
    plot.subtitle = ggplot2::element_text(hjust = 0.5),
    panel.grid.major = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_blank(),
    axis.ticks.x = ggplot2::element_blank(),
    axis.text.y = ggplot2::element_blank(),
    axis.ticks.y = ggplot2::element_blank(),
    strip.text.x = ggplot2::element_blank(),
    strip.background = ggplot2::element_rect(colour = "white", fill = "white"),
    legend.position = "right",
    legend.background = ggplot2::element_rect(fill = "grey90", size = 0.1, linetype = "solid", colour = "black")
  )
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE, results=TRUE }
# Distancia mínima de un radio censal a un establecimiento educativo
distancias.radios.establecimientos <- sf::st_distance(censo, establecimientos)
distancias.minimas                 <- censo %>%
  dplyr::mutate(distancia_minima = apply(distancias.radios.establecimientos, MARGIN = 1, FUN = min),
                porcentaje_nbi = 100 * HOGARES_NBI / HOGARES)
```