---
title: "Data Mining: Trabajo Práctico nº 2"
subtitle: "Análisis de un conjunto de datos de Precios Claros"
author:
- Santiago Rovere (srovere@gmail.com), Facultad de Ingeniería, Universidad de Buenos Aires
- Javier Quinteros (jaqbase-dmkm@yahoo.com.ar), Universidad Argentina de la Empresa
date: '`r format(Sys.Date(), "%d de %B de %Y")`'
output:
  html_document:
    number_sections: yes
    css: styles.css
  pdf_document:
    number_sections: yes
  html_notebook:
    number_sections: yes
header-includes: \usepackage{float}
lang: es
---

```{r, echo=FALSE, warnings=FALSE, message=FALSE }
# Borrar bariables del ambiente
rm(list = objects())

# Carga de paquetes necesarios para hacer los gráficos
require(arules)
require(arulesViz)
require(Cairo)
require(ggplot2)
require(gridExtra)
require(knitr)
require(sf)

# Uso de Cairo para renderizar los gráficos
options(bitmapType = "cairo")

# Ubicar los gráficos en el lugar donde aparece el código
knitr::opts_chunk$set(fig.pos = "H", collapse = TRUE)

# Carga de variables necesarias para realizar el informe
load(file = paste0("input/PreciosClaros.RData"))
load(file = paste0("input/ReglasAsociacion.RData"))
```

# Introducción

El presente trabajo se basa en la exploración y análisis de un conjunto de datos extraído de la aplicación **Precios Claros** [1]. Este conjunto de datos ya fue analizado anteriormente en [2]. En este caso, nos proponemos poner el foco en el análisis a partir de reglas de asociación. El uso de esta técnica nos permitirá extraer nuevo conocimiento del conjunto de datos. También nos permitirá corroborar o reformular afirmaciones realizadas en el trabajo previo.

Sin embargo, si bien el uso de reglas de asociación será la herramienta central de este estudio, no será la única. Se utilizarán también algunas herramientas de *text mining* con el fin de poder clasificar productos a partir de sus datos de descripción, marca y presentación. Incluso también se utilizará análisis de correspondencia para validar algunas conclusiones elaboradas en nuestro trabajo previo.

El presente documento se encuentra organizado de la siguiente manera: en la sección *2* se presentarán los objetivos centrales del análisis; en la sección *3* se detallará el proceso de preparación de datos realizado a fin de poder llevar a cabo los análisis de la sección *4*; finalmente, en la sección *5* se elaborarán las conclusiones finales proponiendo algunas posibles líneas de trabajo futuro.

# Objetivo

De acuerdo a las consignas propuestas en la documentación del trabajo práctico, se abordará la investigación del conjunto de datos a partir del análisis de los siguientes temas:

  * Enfoque descriptivo:
    * Análisis exploratorio de reglas de asociación
    * Búsqueda de factores que expliquen la desaceleración de precios en las últimas mediciones
    * Exploración de reglas asociadas al comportamiento de los precios de un lote de productos seleccionado
  * Enfoque predictivo:
    * Evaluación de reglas que permitan predecir el comportamiento de precios del último período a partir de precios anteriores
    * Validación de resultados expuestos en el trabajo práctivo previo

# Preparación de datos

El primer paso necesario para avanzar sobre la preparación de los datos consiste en averiguar qué variables del conjunto de datos se desean estudiar. Algunas de ellas fueron sugeridas en el enunciado del trabajo práctico (niveles de precios y de variación de los mismos) y otras fueron adicionadas por los autores. En todos los casos, el abordaje consistió en la discretización de las variables continuas y en la reagrupación de variables categóricas.

A continuación, se realizaron todas las transformaciones de precios sugeridas en el enunciado. Por tal motivo, no ahondaremos en detalles de dichas transformaciones, sino que las enumeraremos para dar completitud al presente documento:

  * Agrupación las mediciones en 4 períodos los cuales abarcan las mediciones 1-3, 4-5, 6-7 y 8-10 respectivamente.
  * Discretización los niveles de precios por producto para cada período y para la totalidad de las mediciones. Así, cada precio relevado, fue categorizado según en: *muy barato, moderadamente barato, levemente barato, medio, levemente caso, moderadamente caso y muy caro*.
  * Discretización de los niveles de aumento de precios por producto para los 3 interperíodos (P1-P2, P2-P3 y P3-P4) y para el período total (medición 1 - medición 10). Las categorías son las siguientes: *disminución fuerte, disminución moderada, disminución leve, mantiene, aumento leve, aumento moderado, aumento fuerte*.
  
Luego se utilizaron herramientas de *text mining* para extraer palabras frecuentes de los nombres de los productos a fin de poder utilizar dicha información para seleccionar datos de productos determinados y poder realizar un análisis más específico. Para llevar a cabo esta tarea, se elaboró un vocabulario con todas la palabras incluidas en los nombres de los productos, eliminando números, tildes, espacios, signos de puntuación, marcas, unidades de presentación y términos frecuentes. De ese conjunto de palabras, muchas de ellas se encontraron en varios productos. 

Para eliminar palabras poco frecuentes, se construyó una tabla para indicar la cantidad de productos que contienen a cada término del vocabulario dentro de su descripción. Luego se analizó la distribucion de la variable *cantidad*, encontrándose que el percentil 75 corresponde el valor 4. Esto significa que solamente 25% de los términos tienen una frecuencia mayor o igual a 4. Consideramos a ese valor como el umbral mínimo para determinar si un término es frecuente o no. A partir de dicho umbral, se encontraron 234 términos con los cuales se construyeron una matriz de tipo *término-documento* donde cada una de las filas corresponde a cada uno de los 1000 productos del conjunto de datos. Esta información luego pudo ser integrada al conjunto de precios, a través de la variable *productoId*.

# Análisis realizados

# Conclusiones

# Referencias

[1]   Precios Claros (https://www.preciosclaros.gob.ar)

[2]   Data Mining: Trabajo Práctico nº 1 - Análisis de un conjunto de datos de Precios Claros (https://rpubs.com/srovere/precios-claros)